export const HEADERS_CONFIG = {
    'santri': ["stambuk_pondok", "stambuk_madrasah", "tahun_masuk", "kamar", "madrasah", "kelas", "nisn", "nik", "nama_siswa", "tempat_tanggal_lahir", "jenis_kelamin", "agama", "kewarganegaraan", "anak_ke", "alamat", "dusun_jalan", "rt_rw", "desa_kelurahan", "kecamatan", "kota_kabupaten", "provinsi", "kode_pos", "hobi", "cita_cita", "asal_sekolah", "nama_ayah", "nik_ayah", "tempat_tanggal_lahir_ayah", "pendidikan_ayah", "pekerjaan_ayah", "penghasilan_ayah", "no_telp_ayah", "nama_ibu", "nik_ibu", "tempat_tanggal_lahir_ibu", "pendidikan_ibu", "pekerjaan_ibu", "penghasilan_ibu", "no_telp_ibu", "status_santri", "tanggal_nonaktif", "alasan_nonaktif", "foto_santri", "file_kk", "file_akta", "created_at", "pindah_ke", "tahun_pindah", "tanggal_boyong", "jumlah_saudara", "pendidikan_terakhir", "no_ijazah", "tempat_lahir", "tanggal_lahir", "status_mb"],
    'pengurus': ["foto_pengurus", "nama", "jabatan", "divisi", "no_hp", "tahun_mulai", "tahun_akhir", "status", "tanggal_nonaktif"],
    'keamanan': ["tanggal", "nama_santri", "jenis_pelanggaran", "poin", "takzir", "keterangan", "petugas"],
    'pendidikan': ["tanggal", "nama_santri", "kegiatan", "nilai", "kehadiran", "keterangan", "ustadz"],
    'users': ["fullname", "username", "email", "password", "password_plain", "role", "avatar"],
    'kamar': ["nama_kamar", "asrama", "kapasitas"],
    'kesehatan': ["nama_santri", "mulai_sakit", "gejala", "obat_tindakan", "status_periksa", "keterangan", "biaya_obat"],
    'izin': ["nama_santri", "kelas", "kamar", "alasan", "tanggal_mulai", "tanggal_selesai", "tipe_izin", "keperluan", "penjemput", "status", "petugas", "keterangan"],
    'barang_sitaan': ["tanggal", "nama_santri", "jenis_barang", "nama_barang", "petugas", "status_barang", "keterangan"],
    'keamanan_reg': ["nama_santri", "jenis_barang", "detail_barang", "jenis_kendaraan", "jenis_elektronik", "plat_nomor", "warna", "merk", "aksesoris_1", "aksesoris_2", "aksesoris_3", "keadaan", "kamar_penempatan", "tanggal_registrasi", "petugas_penerima", "keterangan", "status_barang_reg"],
    'layanan_master': ["unit", "nama_layanan", "harga", "status"],
    'layanan_admin': ["tanggal", "unit", "nama_santri", "stambuk", "jenis_layanan", "nominal", "keterangan", "pj", "pemohon_tipe", "jumlah"],
    'arsip_surat': ["tanggal", "nomor_surat", "tipe", "pengirim_penerima", "perihal", "keterangan", "file_surat"],
    'arsip_proposal': ["tanggal", "nomor_proposal", "judul", "pengaju", "nominal", "status", "file_proposal", "keterangan"],
    'arsip_akta_tanah': ["nomor_akta", "tanggal", "lokasi", "luas_tanah", "atas_nama", "status_kepemilikan", "file_akta", "keterangan"],
    'arsip_pengurus_periode': ["periode_mulai", "periode_selesai", "nama", "jabatan", "divisi", "foto_pengurus", "keterangan"],
    'master_kelas': ["lembaga", "nama_kelas", "urutan"],
    'master_jabatan': ["kelompok", "nama_jabatan", "urutan"],
    'master_pembimbing': ["nama_jabatan", "urutan"],
    'master_kategori_pembayaran': ["nama_kategori", "kode", "keterangan", "urutan", "aktif"],
    'keuangan_tarif': ["kategori_status", "kelas", "nominal", "keterangan"],
    'keuangan_pembayaran': ["santri_id", "nama_santri", "tanggal", "jenis_pembayaran", "bulan_tagihan", "nominal", "keterangan", "petugas"],
    'keuangan_status_santri': ["santri_id", "nama_santri", "kategori_pembayaran", "tanggal_mulai", "tanggal_selesai", "keterangan", "petugas"],
    'keuangan_kas': ["tanggal", "tipe", "kategori", "nominal", "keterangan", "pembayaran_id", "petugas"],
    'arus_kas': ["tanggal", "tipe", "kategori", "nominal", "keterangan", "pj"],
    'kas_unit': ["tanggal", "tipe", "kategori", "nominal", "keterangan", "petugas"],
    'kalender_kerja': ["hari", "tanggal_masehi", "tanggal_hijriyah", "nama_kegiatan", "kategori", "file_kalender", "keterangan", "periode"],
    'roles': ["role", "label", "color", "menus", "is_public"],
    'wajar_pengurus': ["nama_pengurus", "kelompok", "jabatan", "keterangan"],
    'wajar_kelompok_mapping': ["santri_id", "nama_santri", "kelompok", "pengurus_id"],
    'wajar_mhm_absen': ["santri_id", "nama_santri", "kelas", "tanggal", "status", "tipe", "petugas"],
    'wajar_miu_absen': ["santri_id", "nama_santri", "kelas", "tanggal", "status", "tipe", "petugas"],
    'wajar_nilai': ["santri_id", "nama_santri", "tanggal", "tipe", "nilai", "materi", "petugas"],
    'keamanan_formal_mapping': ["santri_id", "nama_santri", "kelompok_formal", "kelas_miu", "jenjang", "semester"],
    'absen_sekolah': ["santri_id", "nama_santri", "kelas", "tanggal", "kelompok_formal", "status", "keterangan", "petugas"],
    'pengurus_target': ["pengurus_id", "nama_pengurus", "bulan", "tahun", "target_tugas", "keterangan"],
    'pengurus_absen': ["pengurus_id", "nama_pengurus", "bulan", "tahun", "tugas", "izin", "alfa", "alasan_izin", "petugas"],
    'edu_pengajian': ["tanggal", "qari", "kitab", "waktu", "tempat", "keterangan", "petugas"],
    'edu_lbm_peserta': ["nama_santri", "kelas", "tipe_lbm", "keterangan"],
    'edu_lbm_delegasi': ["tanggal", "nama_santri", "kelas", "acara", "tempat", "hasil", "petugas"],
    'edu_lbm_absen': ["tanggal", "nama_santri", "kelas", "tipe_lbm", "status", "keterangan", "petugas"],
    'edu_sorogan_absen': ["tanggal", "nama_santri", "kelas", "kelompok", "status", "keterangan", "petugas"],
    'edu_sorogan_kelompok': ["nama_santri", "kelas", "kelompok", "pembimbing", "keterangan"],
    'edu_takhosus_seminar': ["tanggal", "materi", "pembimbing", "waktu", "tempat", "peserta", "petugas"],
    'jamiyyah_penasihat': ["kamar", "asrama", "nama_penasihat", "keterangan"],
    'jamiyyah_kelompok': ["nama_kelompok", "wilayah", "jumlah_santri", "ketua", "pembimbing", "keterangan"],
    'unit_lab_media_kas': ["tanggal", "unit", "tipe", "kategori", "nominal", "keterangan", "petugas"],
    'unit_lab_media_tarif': ["unit", "nama_layanan", "harga", "keterangan"]
};

export const FILE_COLUMNS = {
    'santri': ["foto_santri"],
    'pengurus': ["foto_pengurus"],
    'arsip_surat': ["file_surat"],
    'arsip_proposal': ["file_proposal"],
    'arsip_akta_tanah': ["file_akta"],
    'arsip_pengurus_periode': ["foto_pengurus"],
    'kalender_kerja': ["file_kalender"],
    'users': ["avatar"]
};
