ALTER TABLE users ADD COLUMN email TEXT;
ALTER TABLE users ADD COLUMN no_hp TEXT;
ALTER TABLE users ADD COLUMN otp_code TEXT;
ALTER TABLE users ADD COLUMN otp_expires DATETIME;
ALTER TABLE users ADD COLUMN is_verified INTEGER DEFAULT 0;
