export const requiredServerFiles = {
    "version": 1,
    "config": {
        "distDir": ".next",
        "cacheComponents": false,
        "htmlLimitedBots": "[\\w-]+-Google|Google-[\\w-]+|Chrome-Lighthouse|Slurp|DuckDuckBot|baiduspider|yandex|sogou|bitlybot|tumblr|vkShare|quora link preview|redditbot|ia_archiver|Bingbot|BingPreview|applebot|facebookexternalhit|facebookcatalog|Twitterbot|LinkedInBot|Slackbot|Discordbot|WhatsApp|SkypeUriPreview|Yeti|googleweblight",
        "assetPrefix": "",
        "output": "standalone",
        "trailingSlash": false,
        "images": {
            "deviceSizes": [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
            "imageSizes": [32, 48, 64, 96, 128, 256, 384],
            "path": "/_next/image",
            "loader": "default",
            "loaderFile": "",
            "domains": [],
            "disableStaticImages": false,
            "minimumCacheTTL": 14400,
            "formats": ["image/webp"],
            "maximumRedirects": 3,
            "dangerouslyAllowLocalIP": false,
            "dangerouslyAllowSVG": false,
            "contentSecurityPolicy": "script-src 'none'; frame-src 'none'; sandbox;",
            "contentDispositionType": "attachment",
            "localPatterns": [{ "pathname": "**", "search": "" }],
            "remotePatterns": [],
            "qualities": [75],
            "unoptimized": true
        },
        "reactMaxHeadersLength": 6000,
        "cacheLife": {
            "default": { "stale": 300, "revalidate": 900, "expire": 4294967294 },
            "seconds": { "stale": 30, "revalidate": 1, "expire": 60 },
            "minutes": { "stale": 300, "revalidate": 60, "expire": 3600 },
            "hours": { "stale": 300, "revalidate": 3600, "expire": 86400 },
            "days": { "stale": 300, "revalidate": 86400, "expire": 604800 },
            "weeks": { "stale": 300, "revalidate": 604800, "expire": 2592000 },
            "max": { "stale": 300, "revalidate": 2592000, "expire": 31536000 }
        },
        "basePath": "",
        "expireTime": 31536000,
        "generateEtags": true,
        "poweredByHeader": true,
        "cacheHandlers": {},
        "cacheMaxMemorySize": 52428800,
        "compress": true,
        "i18n": null,
        "httpAgentOptions": { "keepAlive": true },
        "pageExtensions": ["tsx", "ts", "jsx", "js"],
        "useFileSystemPublicRoutes": true,
        "experimental": {
            "ppr": false,
            "staleTimes": { "dynamic": 0, "static": 300 },
            "dynamicOnHover": false,
            "inlineCss": false,
            "authInterrupts": false,
            "fetchCacheKeyPrefix": "",
            "isrFlushToDisk": true,
            "optimizeCss": false,
            "nextScriptWorkers": false,
            "disableOptimizedLoading": false,
            "largePageDataBytes": 128000,
            "serverComponentsHmrCache": true,
            "caseSensitiveRoutes": false,
            "validateRSCRequestHeaders": false,
            "useSkewCookie": false,
            "preloadEntriesOnStart": true,
            "hideLogsAfterAbort": false,
            "removeUncaughtErrorAndRejectionListeners": false,
            "imgOptConcurrency": null,
            "imgOptMaxInputPixels": 268402689,
            "imgOptSequentialRead": null,
            "imgOptSkipMetadata": null,
            "imgOptTimeoutInSeconds": 7,
            "proxyClientMaxBodySize": 10485760,
            "trustHostHeader": false,
            "isExperimentalCompile": false
        }
    },
    "appDir": "C:\\Users\\ppdsl\\Music\\Dashbord Admin",
    "relativeAppDir": "",
    "files": [],
    "ignore": []
};

export const buildId = "V5561SmbUO-GIX47df2lb";

export const routesManifest = {
    "version": 3,
    "pages404": true,
    "appType": "app",
    "caseSensitive": false,
    "basePath": "",
    "redirects": [
        {
            "source": "/:path+/",
            "destination": "/:path+",
            "internal": true,
            "priority": true,
            "statusCode": 308,
            "regex": "^(?:/((?:[^/]+?)(?:/(?:[^/]+?))*))/$"
        }
    ],
    "headers": [],
    "rewrites": {
        "beforeFiles": [],
        "afterFiles": [],
        "fallback": []
    },
    "dynamicRoutes": [],
    "staticRoutes": [
        { "page": "/", "regex": "^/(?:/)?$", "routeKeys": {}, "namedRegex": "^/(?:/)?$" },
        { "page": "/_global-error", "regex": "^/_global\\-error(?:/)?$", "routeKeys": {}, "namedRegex": "^/_global\\-error(?:/)?$" },
        { "page": "/_not-found", "regex": "^/_not\\-found(?:/)?$", "routeKeys": {}, "namedRegex": "^/_not\\-found(?:/)?$" },
        { "page": "/akses", "regex": "^/akses(?:/)?$", "routeKeys": {}, "namedRegex": "^/akses(?:/)?$" },
        { "page": "/api", "regex": "^/api(?:/)?$", "routeKeys": {}, "namedRegex": "^/api(?:/)?$" },
        { "page": "/bendahara/arus-kas", "regex": "^/bendahara/arus\\-kas(?:/)?$", "routeKeys": {}, "namedRegex": "^/bendahara/arus\\-kas(?:/)?$" },
        { "page": "/bendahara/atur-layanan", "regex": "^/bendahara/atur\\-layanan(?:/)?$", "routeKeys": {}, "namedRegex": "^/bendahara/atur\\-layanan(?:/)?$" },
        { "page": "/bendahara/kas-unit", "regex": "^/bendahara/kas\\-unit(?:/)?$", "routeKeys": {}, "namedRegex": "^/bendahara/kas\\-unit(?:/)?$" },
        { "page": "/bendahara/riwayat-presensi", "regex": "^/bendahara/riwayat\\-presensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/bendahara/riwayat\\-presensi(?:/)?$" },
        { "page": "/dashboard", "regex": "^/dashboard(?:/)?$", "routeKeys": {}, "namedRegex": "^/dashboard(?:/)?$" },
        { "page": "/develzy", "regex": "^/develzy(?:/)?$", "routeKeys": {}, "namedRegex": "^/develzy(?:/)?$" },
        { "page": "/favicon.ico", "regex": "^/favicon\\.ico(?:/)?$", "routeKeys": {}, "namedRegex": "^/favicon\\.ico(?:/)?$" },
        { "page": "/jamiyyah/layanan", "regex": "^/jamiyyah/layanan(?:/)?$", "routeKeys": {}, "namedRegex": "^/jamiyyah/layanan(?:/)?$" },
        { "page": "/jamiyyah/manajemen", "regex": "^/jamiyyah/manajemen(?:/)?$", "routeKeys": {}, "namedRegex": "^/jamiyyah/manajemen(?:/)?$" },
        { "page": "/jamiyyah/penasihat", "regex": "^/jamiyyah/penasihat(?:/)?$", "routeKeys": {}, "namedRegex": "^/jamiyyah/penasihat(?:/)?$" },
        { "page": "/jamiyyah/riwayat-presensi", "regex": "^/jamiyyah/riwayat\\-presensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/jamiyyah/riwayat\\-presensi(?:/)?$" },
        { "page": "/keamanan/absensi-formal", "regex": "^/keamanan/absensi\\-formal(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/absensi\\-formal(?:/)?$" },
        { "page": "/keamanan/absensi-formal/riwayat", "regex": "^/keamanan/absensi\\-formal/riwayat(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/absensi\\-formal/riwayat(?:/)?$" },
        { "page": "/keamanan/barang-sitaan", "regex": "^/keamanan/barang\\-sitaan(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/barang\\-sitaan(?:/)?$" },
        { "page": "/keamanan/izin", "regex": "^/keamanan/izin(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/izin(?:/)?$" },
        { "page": "/keamanan/layanan", "regex": "^/keamanan/layanan(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/layanan(?:/)?$" },
        { "page": "/keamanan/pelanggaran", "regex": "^/keamanan/pelanggaran(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/pelanggaran(?:/)?$" },
        { "page": "/keamanan/pengaturan-formal", "regex": "^/keamanan/pengaturan\\-formal(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/pengaturan\\-formal(?:/)?$" },
        { "page": "/keamanan/registrasi-barang", "regex": "^/keamanan/registrasi\\-barang(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/registrasi\\-barang(?:/)?$" },
        { "page": "/keamanan/riwayat-presensi", "regex": "^/keamanan/riwayat\\-presensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/keamanan/riwayat\\-presensi(?:/)?$" },
        { "page": "/kesehatan", "regex": "^/kesehatan(?:/)?$", "routeKeys": {}, "namedRegex": "^/kesehatan(?:/)?$" },
        { "page": "/kesehatan/layanan", "regex": "^/kesehatan/layanan(?:/)?$", "routeKeys": {}, "namedRegex": "^/kesehatan/layanan(?:/)?$" },
        { "page": "/kesehatan/riwayat-presensi", "regex": "^/kesehatan/riwayat\\-presensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/kesehatan/riwayat\\-presensi(?:/)?$" },
        { "page": "/keuangan/arus-kas", "regex": "^/keuangan/arus\\-kas(?:/)?$", "routeKeys": {}, "namedRegex": "^/keuangan/arus\\-kas(?:/)?$" },
        { "page": "/keuangan/kategori-pembayaran", "regex": "^/keuangan/kategori\\-pembayaran(?:/)?$", "routeKeys": {}, "namedRegex": "^/keuangan/kategori\\-pembayaran(?:/)?$" },
        { "page": "/keuangan/pembayaran", "regex": "^/keuangan/pembayaran(?:/)?$", "routeKeys": {}, "namedRegex": "^/keuangan/pembayaran(?:/)?$" },
        { "page": "/keuangan/pengaturan", "regex": "^/keuangan/pengaturan(?:/)?$", "routeKeys": {}, "namedRegex": "^/keuangan/pengaturan(?:/)?$" },
        { "page": "/keuangan/status-santri", "regex": "^/keuangan/status\\-santri(?:/)?$", "routeKeys": {}, "namedRegex": "^/keuangan/status\\-santri(?:/)?$" },
        { "page": "/lab-media/histori", "regex": "^/lab\\-media/histori(?:/)?$", "routeKeys": {}, "namedRegex": "^/lab\\-media/histori(?:/)?$" },
        { "page": "/lab-media/lab", "regex": "^/lab\\-media/lab(?:/)?$", "routeKeys": {}, "namedRegex": "^/lab\\-media/lab(?:/)?$" },
        { "page": "/lab-media/media", "regex": "^/lab\\-media/media(?:/)?$", "routeKeys": {}, "namedRegex": "^/lab\\-media/media(?:/)?$" },
        { "page": "/lab-media/riwayat-presensi", "regex": "^/lab\\-media/riwayat\\-presensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/lab\\-media/riwayat\\-presensi(?:/)?$" },
        { "page": "/lab-media/tarif", "regex": "^/lab\\-media/tarif(?:/)?$", "routeKeys": {}, "namedRegex": "^/lab\\-media/tarif(?:/)?$" },
        { "page": "/laporan", "regex": "^/laporan(?:/)?$", "routeKeys": {}, "namedRegex": "^/laporan(?:/)?$" },
        { "page": "/pendidikan", "regex": "^/pendidikan(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan(?:/)?$" },
        { "page": "/pendidikan/layanan", "regex": "^/pendidikan/layanan(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/layanan(?:/)?$" },
        { "page": "/pendidikan/lbm/delegasi", "regex": "^/pendidikan/lbm/delegasi(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/lbm/delegasi(?:/)?$" },
        { "page": "/pendidikan/lbm/malam", "regex": "^/pendidikan/lbm/malam(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/lbm/malam(?:/)?$" },
        { "page": "/pendidikan/lbm/pagi", "regex": "^/pendidikan/lbm/pagi(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/lbm/pagi(?:/)?$" },
        { "page": "/pendidikan/pengajian", "regex": "^/pendidikan/pengajian(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/pengajian(?:/)?$" },
        { "page": "/pendidikan/riwayat-presensi", "regex": "^/pendidikan/riwayat\\-presensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/riwayat\\-presensi(?:/)?$" },
        { "page": "/pendidikan/sorogan/absen", "regex": "^/pendidikan/sorogan/absen(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/sorogan/absen(?:/)?$" },
        { "page": "/pendidikan/sorogan/kelompok", "regex": "^/pendidikan/sorogan/kelompok(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/sorogan/kelompok(?:/)?$" },
        { "page": "/pendidikan/takhosus", "regex": "^/pendidikan/takhosus(?:/)?$", "routeKeys": {}, "namedRegex": "^/pendidikan/takhosus(?:/)?$" },
        { "page": "/presensi/generator", "regex": "^/presensi/generator(?:/)?$", "routeKeys": {}, "namedRegex": "^/presensi/generator(?:/)?$" },
        { "page": "/presensi/generator-static", "regex": "^/presensi/generator\\-static(?:/)?$", "routeKeys": {}, "namedRegex": "^/presensi/generator\\-static(?:/)?$" },
        { "page": "/presensi/riwayat", "regex": "^/presensi/riwayat(?:/)?$", "routeKeys": {}, "namedRegex": "^/presensi/riwayat(?:/)?$" },
        { "page": "/presensi/scan", "regex": "^/presensi/scan(?:/)?$", "routeKeys": {}, "namedRegex": "^/presensi/scan(?:/)?$" },
        { "page": "/sekretariat/absen-pengurus", "regex": "^/sekretariat/absen\\-pengurus(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/absen\\-pengurus(?:/)?$" },
        { "page": "/sekretariat/absen-pengurus/riwayat", "regex": "^/sekretariat/absen\\-pengurus/riwayat(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/absen\\-pengurus/riwayat(?:/)?$" },
        { "page": "/sekretariat/arsip/akta-tanah", "regex": "^/sekretariat/arsip/akta\\-tanah(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/arsip/akta\\-tanah(?:/)?$" },
        { "page": "/sekretariat/arsip/alumni", "regex": "^/sekretariat/arsip/alumni(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/arsip/alumni(?:/)?$" },
        { "page": "/sekretariat/arsip/mutasi-santri", "regex": "^/sekretariat/arsip/mutasi\\-santri(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/arsip/mutasi\\-santri(?:/)?$" },
        { "page": "/sekretariat/arsip/pengurus-periode", "regex": "^/sekretariat/arsip/pengurus\\-periode(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/arsip/pengurus\\-periode(?:/)?$" },
        { "page": "/sekretariat/arsip/proposal", "regex": "^/sekretariat/arsip/proposal(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/arsip/proposal(?:/)?$" },
        { "page": "/sekretariat/arsip/surat", "regex": "^/sekretariat/arsip/surat(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/arsip/surat(?:/)?$" },
        { "page": "/sekretariat/kalender", "regex": "^/sekretariat/kalender(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/kalender(?:/)?$" },
        { "page": "/sekretariat/kamar", "regex": "^/sekretariat/kamar(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/kamar(?:/)?$" },
        { "page": "/sekretariat/layanan", "regex": "^/sekretariat/layanan(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/layanan(?:/)?$" },
        { "page": "/sekretariat/pengurus", "regex": "^/sekretariat/pengurus(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/pengurus(?:/)?$" },
        { "page": "/sekretariat/santri", "regex": "^/sekretariat/santri(?:/)?$", "routeKeys": {}, "namedRegex": "^/sekretariat/santri(?:/)?$" },
        { "page": "/wajar-murottil/murottil-malam", "regex": "^/wajar\\-murottil/murottil\\-malam(?:/)?$", "routeKeys": {}, "namedRegex": "^/wajar\\-murottil/murottil\\-malam(?:/)?$" },
        { "page": "/wajar-murottil/murottil-pagi", "regex": "^/wajar\\-murottil/murottil\\-pagi(?:/)?$", "routeKeys": {}, "namedRegex": "^/wajar\\-murottil/murottil\\-pagi(?:/)?$" },
        { "page": "/wajar-murottil/pengaturan", "regex": "^/wajar\\-murottil/pengaturan(?:/)?$", "routeKeys": {}, "namedRegex": "^/wajar\\-murottil/pengaturan(?:/)?$" },
        { "page": "/wajar-murottil/riwayat-absensi", "regex": "^/wajar\\-murottil/riwayat\\-absensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/wajar\\-murottil/riwayat\\-absensi(?:/)?$" },
        { "page": "/wajar-murottil/riwayat-presensi", "regex": "^/wajar\\-murottil/riwayat\\-presensi(?:/)?$", "routeKeys": {}, "namedRegex": "^/wajar\\-murottil/riwayat\\-presensi(?:/)?$" },
        { "page": "/wajar-murottil/wajib-belajar", "regex": "^/wajar\\-murottil/wajib\\-belajar(?:/)?$", "routeKeys": {}, "namedRegex": "^/wajar\\-murottil/wajib\\-belajar(?:/)?$" }
    ],
    "dataRoutes": [],
    "rsc": {
        "header": "rsc",
        "varyHeader": "rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch",
        "prefetchHeader": "next-router-prefetch",
        "didPostponeHeader": "x-nextjs-postponed",
        "contentTypeHeader": "text/x-component",
        "suffix": ".rsc",
        "prefetchSegmentHeader": "next-router-segment-prefetch",
        "prefetchSegmentSuffix": ".segment.rsc",
        "prefetchSegmentDirSuffix": ".segments",
        "clientParamParsing": false,
        "dynamicRSCPrerender": false
    },
    "rewriteHeaders": {
        "pathHeader": "x-nextjs-rewritten-path",
        "queryHeader": "x-nextjs-rewritten-query"
    }
};

export const pagesManifest = {
    "/404": "pages/404.html",
    "/500": "pages/500.html"
};

export const middlewareManifest = {
    "version": 3,
    "middleware": {},
    "functions": {},
    "sortedMiddleware": []
};

export const functionsConfigManifest = {
    "version": 1,
    "functions": {}
};

export const appPathRoutesManifest = {
    "/_not-found/page": "/_not-found",
    "/_global-error/page": "/_global-error",
    "/api/route": "/api",
    "/favicon.ico/route": "/favicon.ico",
    "/akses/page": "/akses",
    "/bendahara/riwayat-presensi/page": "/bendahara/riwayat-presensi",
    "/bendahara/atur-layanan/page": "/bendahara/atur-layanan",
    "/bendahara/arus-kas/page": "/bendahara/arus-kas",
    "/bendahara/kas-unit/page": "/bendahara/kas-unit",
    "/dashboard/page": "/dashboard",
    "/jamiyyah/riwayat-presensi/page": "/jamiyyah/riwayat-presensi",
    "/jamiyyah/layanan/page": "/jamiyyah/layanan",
    "/keamanan/absensi-formal/page": "/keamanan/absensi-formal",
    "/jamiyyah/penasihat/page": "/jamiyyah/penasihat",
    "/jamiyyah/manajemen/page": "/jamiyyah/manajemen",
    "/keamanan/absensi-formal/riwayat/page": "/keamanan/absensi-formal/riwayat",
    "/keamanan/layanan/page": "/keamanan/layanan",
    "/keamanan/izin/page": "/keamanan/izin",
    "/keamanan/pengaturan-formal/page": "/keamanan/pengaturan-formal",
    "/kesehatan/layanan/page": "/kesehatan/layanan",
    "/keamanan/barang-sitaan/page": "/keamanan/barang-sitaan",
    "/keamanan/riwayat-presensi/page": "/keamanan/riwayat-presensi",
    "/keamanan/pelanggaran/page": "/keamanan/pelanggaran",
    "/kesehatan/riwayat-presensi/page": "/kesehatan/riwayat-presensi",
    "/kesehatan/page": "/kesehatan",
    "/keamanan/registrasi-barang/page": "/keamanan/registrasi-barang",
    "/keuangan/pengaturan/page": "/keuangan/pengaturan",
    "/keuangan/pembayaran/page": "/keuangan/pembayaran",
    "/keuangan/arus-kas/page": "/keuangan/arus-kas",
    "/lab-media/histori/page": "/lab-media/histori",
    "/keuangan/status-santri/page": "/keuangan/status-santri",
    "/keuangan/kategori-pembayaran/page": "/keuangan/kategori-pembayaran",
    "/lab-media/riwayat-presensi/page": "/lab-media/riwayat-presensi",
    "/lab-media/lab/page": "/lab-media/lab",
    "/lab-media/tarif/page": "/lab-media/tarif",
    "/laporan/page": "/laporan",
    "/pendidikan/lbm/delegasi/page": "/pendidikan/lbm/delegasi",
    "/lab-media/media/page": "/lab-media/media",
    "/pendidikan/layanan/page": "/pendidikan/layanan",
    "/pendidikan/sorogan/kelompok/page": "/pendidikan/sorogan/kelompok",
    "/pendidikan/lbm/pagi/page": "/pendidikan/lbm/pagi",
    "/pendidikan/riwayat-presensi/page": "/pendidikan/riwayat-presensi",
    "/pendidikan/page": "/pendidikan",
    "/pendidikan/pengajian/page": "/pendidikan/pengajian",
    "/pendidikan/lbm/malam/page": "/pendidikan/lbm/malam",
    "/pendidikan/takhosus/page": "/pendidikan/takhosus",
    "/presensi/scan/page": "/presensi/scan",
    "/pendidikan/sorogan/absen/page": "/pendidikan/sorogan/absen",
    "/presensi/generator-static/page": "/presensi/generator-static",
    "/presensi/riwayat/page": "/presensi/riwayat",
    "/sekretariat/arsip/akta-tanah/page": "/sekretariat/arsip/akta-tanah",
    "/presensi/generator/page": "/presensi/generator",
    "/sekretariat/absen-pengurus/page": "/sekretariat/absen-pengurus",
    "/sekretariat/arsip/mutasi-santri/page": "/sekretariat/arsip/mutasi-santri",
    "/sekretariat/layanan/page": "/sekretariat/layanan",
    "/sekretariat/arsip/alumni/page": "/sekretariat/arsip/alumni",
    "/sekretariat/absen-pengurus/riwayat/page": "/sekretariat/absen-pengurus/riwayat",
    "/sekretariat/arsip/proposal/page": "/sekretariat/arsip/proposal",
    "/sekretariat/arsip/pengurus-periode/page": "/sekretariat/arsip/pengurus-periode",
    "/wajar-murottil/murottil-malam/page": "/wajar-murottil/murottil-malam",
    "/sekretariat/kalender/page": "/sekretariat/kalender",
    "/sekretariat/pengurus/page": "/sekretariat/pengurus",
    "/sekretariat/kamar/page": "/sekretariat/kamar",
    "/wajar-murottil/murottil-pagi/page": "/wajar-murottil/murottil-pagi",
    "/wajar-murottil/riwayat-presensi/page": "/wajar-murottil/riwayat-presensi",
    "/sekretariat/arsip/surat/page": "/sekretariat/arsip/surat",
    "/wajar-murottil/pengaturan/page": "/wajar-murottil/pengaturan",
    "/sekretariat/santri/page": "/sekretariat/santri",
    "/wajar-murottil/riwayat-absensi/page": "/wajar-murottil/riwayat-absensi",
    "/wajar-murottil/wajib-belajar/page": "/wajar-murottil/wajib-belajar",
    "/develzy/page": "/develzy",
    "/page": "/"
};

export const prerenderManifest = {
    "version": 4,
    "routes": {}
};
